export const projectsDatas = [

    {
        id: 1,
        theme: 'light',
        title: "Site Vitrine",
        date: "janvier 22",
        languages: ["React", "Styled Components"],
        infos: "Exemple de site vitrine pour une entreprise de tech, avec un design dans l'ère du temps, fait en 100% React JS, modulable, donc facilement modifiable pour quiconque, et ce sans base de données, avec la possibilité de changer les photos, les textes, tout en choisissant entre un thème Dark ou Light, et l'ordre texte / photo de l'article, pour une mise en page optimale.",
        img: "./assets/img/projet-3.jpg",
        link: "http://exemple-vitrine.white-umbrella.fr/",
    },
    {
        id: 2,
        theme: 'dark',
        title: "E-Shop",
        date: "janvier 22",
        languages: ["HTML", "CSS", "PHP", "SQL"],
        infos: "Site E-Commerce sur le thème de la vape, réalisé from scratch, entièrement sans frameworks, avec un max de features : gestion de stocks / paniers, comptes clients, factures, module de paiement Stripe, livraison, gestion d'adresse / messagerie interne directe avec les vendeurs, interface de gestion pour les vendeurs et administrateurs / interface de création d'annonce et caroussel de photos / pagination automatique et tri par catégorie d'articles.",
        img: "./assets/img/projet-2.jpg",
        link: "http://vape-swap-club.white-umbrella.fr/",
    },
    {
        id: 3,
        theme: 'light',
        title: "Foodtruck",
        date: "janvier 22",
        languages: ["HTML", "CSS3", "PHP", "Symfony"],
        infos: "Landing page pour un foodtruck sur le thème de KFC réalisé avec Symfony pour la structure, mais en CSS from scratch pour le web design et un peu de JavaScript, pour quelques fonctionnalités. Possibilité de mettre en avant des menus sur un caroussel, articles de blog, lien vers app smartphone, récupération du feed Facebook ou Instagram pour mettre en avant certains posts / commentaires clients, vidéo B-Roll de présentation du foodtruck, lien vers réseaux sociaux.",
        img: "./assets/img/projet-1.jpg",
        link: "http://foodtruck.white-umbrella.fr/",
    },
    {
        id: 4,
        theme: 'dark',
        title: "Blog",
        date: "janvier 22",
        languages: ["HTML", "CSS3", "PHP", "Symfony"],
        infos: "Blog musical sur le thème de la culture HipHop, réalisé pour la structure principale en Symfony, le design en CSS3, et ensuite la gestion des utilisateurs / commentaires en React JS en passant par une API faite 'à la main' avec PHP / Symfony, afin d'avoir un accès sécurisé aux données sensibles. Récupération du feed Instagram afin d'afficher les derniers posts / Tri des articles par catégories / affichage des articles récents en caroussel / affichage des articles populaires en sidebar / fonction de recherche.",
        img: "./assets/img/projet-4.jpg",
        link: "https://the-square.net",
    },
    {
        id: 5,
        theme: 'light',
        title: "80's Flix",
        date: "janvier 22",
        languages: ["HTML", "Bootstrap", "PHP", "Symfony"],
        infos: "Base de donnée de séries TV à mi-chemin entre IMDDB & Netflix, répertoriant les séries TV, réalisé avec Symfony & Bootstrap. Affichage des dernières séries ajoutées sur la page d'accueil, option de likes, liste de favoris, compte utilisateur, interface d'administration permettant de gérer les séries, ajouter des personnages, des images, des saisons, des catégories, ainsi que la gestion des utilisateurs du site web.",
        img: "./assets/img/projet-5.jpg",
        link: "https://the-square.net",
    }
]