export const projectsDatas = [

    {
        id: 1,
        theme: 'dark',
        title: "Site Vitrine",
        date: "janvier 22",
        languages: ["React", "Styled Components"],
        infos: "Laboris ad enim ea aliqua qui sunt veniam do occaecat. Consectetur incididunt occaecat aliqua non mollit consectetur nisi nisi cupidatat. Nulla laboris in dolor ut sint ullamco laborum nulla anim voluptate veniam. Ex deserunt ipsum ut veniam culpa reprehenderit enim officia Lorem culpa commodo mollit minim cillum. Ipsum laboris magna velit aute excepteur mollit aliquip veniam sunt minim ullamco.",
        img: "./assets/img/projet-3.jpg",
        link: "https://the-square.net",
    },
    {
        id: 2,
        theme: 'light',
        title: "E-Shop",
        date: "janvier 22",
        languages: ["HTML", "CSS", "PHP"],
        infos: "Consequat eu dolore et aute et Lorem ad. Amet laborum pariatur velit qui nisi tempor commodo Lorem tempor aliquip ipsum proident non excepteur. Cillum duis aute culpa non aute irure nulla do nostrud commodo cillum eiusmod ea. Est mollit ipsum culpa officia id ipsum cillum. Fugiat reprehenderit esse ullamco do aliqua. Amet ipsum Lorem fugiat nulla quis minim cillum adipisicing in mollit magna adipisicing.",
        img: "./assets/img/projet-2.jpg",
        link: "https://the-square.net",
    },
    {
        id: 3,
        theme: 'dark',
        title: "Foodtruck",
        date: "janvier 22",
        languages: ["HTML", "CSS3", "PHP", "Symfony"],
        infos: "Minim laboris ipsum tempor duis do in eu duis esse nulla. Lorem ex nisi mollit adipisicing et sint minim laboris dolore minim. Est occaecat quis exercitation Lorem esse aliqua consectetur dolore officia.",
        img: "./assets/img/projet-1.jpg",
        link: "https://the-square.net",
    },
    {
        id: 4,
        theme: 'light',
        title: "Blog",
        date: "janvier 22",
        languages: ["HTML", "CSS3", "PHP", "Symfony"],
        infos: "Nostrud adipisicing adipisicing anim id aliqua labore cupidatat non qui enim pariatur sit. Adipisicing esse culpa nulla laboris sunt culpa voluptate laboris veniam reprehenderit consequat sunt dolore. Eu eu officia amet ut occaecat est ut. Ad eiusmod veniam excepteur Lorem ipsum.",
        img: "./assets/img/projet-4.jpg",
        link: "https://the-square.net",
    },
    {
        id: 5,
        theme: 'dark',
        title: "80's Flix",
        date: "janvier 22",
        languages: ["HTML", "CSS3", "PHP", "Symfony"],
        infos: "Nostrud adipisicing adipisicing anim id aliqua labore cupidatat non qui enim pariatur sit. Adipisicing esse culpa nulla laboris sunt culpa voluptate laboris veniam reprehenderit consequat sunt dolore. Eu eu officia amet ut occaecat est ut. Ad eiusmod veniam excepteur Lorem ipsum.",
        img: "./assets/img/projet-5.jpg",
        link: "https://the-square.net",
    }
]